image: node:lts-slim

stages:
  - package

.dockerize-template:
  image: docker:stable
  stage: package
  cache: {}
  services:
    - docker:stable-dind
  variables:
    DOCKER_FILE: ./Dockerfile
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
    - docker build --pull -t "$DOCKER_IMAGE_TAG" -f $DOCKER_FILE .
    - docker push "$DOCKER_IMAGE_TAG"

dockerize:latest:
  extends: .dockerize-template
  variables:
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_MERGE_REQUEST_ID # Avoid special merge request pipeline
      when: never
    - if: $CI_COMMIT_TAG # Avoid special tag pipeline
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Running rule
      when: on_success

dockerize:branch:
  extends: .dockerize-template
  rules:
    - if: $CI_MERGE_REQUEST_ID # Avoid special merge request pipeline
      when: never
    - if: $CI_COMMIT_TAG # Avoid special tag pipeline
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # Running rule
      when: on_success

dockerize:tag:
  extends: dockerize:latest
  variables:
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_MERGE_REQUEST_ID # Avoid special merge request pipeline
      when: never
    - if: $CI_COMMIT_TAG # Running rule
      when: on_success
