---
# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - local: .gitlab/package.gitlab-ci.yml

stages:
  - test
  - package
  - security

variables:
  CS_MAJOR_VERSION: 4 # remove after upgrade to GitLab >= 14
# ----------------------------------------------------------------------
# security
# ----------------------------------------------------------------------
container_scanning_new: # rename to container_scanning after migration to GitLab >= 14
  stage: security
  variables:
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        export DOCKER_IMAGE="$CI_REGISTRY_IMAGE:latest"
      fi
