---
.dockerize-template:
  image: docker:stable
  stage: package
  cache: {}
  services:
    - docker:stable-dind
  variables:
    DOCKER_FILE: ./Dockerfile
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG # r.am.hilti.com/wfm-web:(branch|tag)
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
    - docker build --pull -t "$DOCKER_IMAGE_TAG" -f $DOCKER_FILE .
    - docker push "$DOCKER_IMAGE_TAG"

dockerize:latest:
  extends: .dockerize-template
  variables:
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never

dockerize:branch:
  extends: .dockerize-template
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_COMMIT_TAG
      when: never
    - when: on_success

dockerize:tag:
  extends: dockerize:latest
  variables:
    DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
